### PR TITLE
🗃 performing changes to database (no error!)

### PR DESCRIPTION
**Pull request by cesar-ca**
In this pull request, the models are refactored because there was an error on every model

Error: A column called 'id' was added to the attributes of 'Devices' but not marked with 'primaryKey: true'

Now, the error should not be there!

### CODE REVIEW

**Comment by cesar-ca** [comment]
This branch is called register and login because I wanted to create register and login forms but couldn't do them before fixing the bugs in the models

**Comment by ZizoGithub** [comment]
Looks good to me

**Comment by francisli** [comment]
So, it looks like "id:integer" was specified in the attributes for the sequelize model:generate command, which is not necessary- sequelize will automatically add the id column for you.

@AndresMartin510 did you create the models? If so, then it looks like you did NOT actually run the migrations afterwards to test if they run correctly.

When creating models, always run sequelize db:migrate afterwards to ensure there are no errors and the migration runs successfully.

**Comment by francisli** [comment]
I'm going to pull down this branch and take a closer look at the models before this gets merged in...

**Review by ZizoGithub — APPROVED** [review]

**Pull request merged**
