### PR TITLE
Home page design

### PR DESCRIPTION
**Pull request by ZizoGithub**
Added the filler text that was missing and some images

### CODE REVIEW

**Comment by cesar-ca** [comment]
Bro

**Comment by cesar-ca** [comment]
Stop working on this branch.... CREATE A NEW ONE... OR if this is a new one, try to have different names for branches and pull requests even if they do similar work

**Comment by cesar-ca** [comment]
I think we had merged both branch and PR with "home page design" name

**Comment by ZizoGithub** [comment]
Ik that but I was making changes to the home page and rn this are minor changes

**Comment by ZizoGithub** [comment]
You can clearly see the files changed are that there were pictures added and I updated the tagline

**Review by AndresMartin510 — COMMENTED** [review]
gud

**Review by AndresMartin510 — APPROVED** [review]
gud

**Pull request merged**
