### PR TITLE
Zizo branch

### PR DESCRIPTION
**Pull request by ZizoGithub**
I changed the readme file to say "Tech-Equity" instead of full-stack starter on line 1. I also added a basic HTML <p> to test it out in home.js which can be erased later on.

### CODE REVIEW

**Review by francisli — CHANGES_REQUESTED** [review]
Add a section for the Team, and add your name.

**Comment by ZizoGithub** [comment]
test comment

**Comment by ZizoGithub** [comment]
[Completed] Added our team and names

**Review by cesar-ca — APPROVED** [review]
Changes look good to me!

**Pull request merged**
