### PR TITLE
Creating front-end forms for updating user profile

### PR DESCRIPTION
**Pull request by cesar-ca**
Beginning to update UI as per designs (DO NOT MERGE YET!)

### CODE REVIEW

**Comment by ZizoGithub** [comment]
Gotcha, looks good so far but I will wait till you are done

**Comment by cesar-ca** [comment]
In this pull request, I created the form to update user profile based on design 

Screen Shot 2021-05-05 at 8 33 08 PM




https://user-images.githubusercontent.com/44204337/117238139-39914280-ade1-11eb-86d0-f60be47d9c6e.mov


Still needs a lot of work, and needs to be connected to the backend, but this is ready to be merged

Also, needs work with Authorization (in this version, anyone can visit the update settings page but it should be restricted only for logged in users)

**Comment by cesar-ca** [comment]
@ZizoGithub @AndresMartin510

**Review by ZizoGithub — COMMENTED** [review]
Looks good to me, feel free to merge it

**Pull request merged**
