### PR TITLE
CRUD userflow for setting up profile 

### PR DESCRIPTION
**Pull request by cesar-ca**
[DO NOT MERGE YET!] 

In this pull request: finishing CRUD user flow for setting up profile details

https://user-images.githubusercontent.com/44204337/118789622-ce685700-b849-11eb-9de7-296d3bb685ec.mov

### CODE REVIEW

**Comment by cesar-ca** [comment]
THIS CAN BE MERGED NOW (It's not done but it can be merged)

** I might need some help with some parts

**Comment by cesar-ca** [comment]
Screen Shot 2021-05-19 at 7 14 39 AM

**Comment by ZizoGithub** [comment]
This form is for the non-profit partners right?

**Comment by cesar-ca** [comment]
This form as is currently is for donor using donor database model (new) and migrations (new). I can replicate it for non-profit and program directors which also need new models and migrations.

**Comment by ZizoGithub** [comment]
Okay got it, page looks good so far though. I have already made the CRUD functions for the Program Directors and made the new models/migrations to go with it if you wanna check out my pull request.

**Comment by francisli** [comment]
I've created a separate PR with Cesar's Donor CRUD implementation here: https://github.com/dev-mission/techequity/pull/27

So, I'm going to close this PR... I will review and revise the ProgramDirector implementation that is in Zizo's branch/PR...

**Pull request closed without merging**
